spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false

  profiles:
    include: oauth, real